image: docker.oxygene.sk/acoustid/chromaprint-build

stages:
  - download
  - build

variables:
  FFMPEG_VERSION: "3.2"

tarball:
  stage: download
  script:
    - wget http://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2
  tags:
    - docker

build:linux-i686:
  stage: build
  script: ARCH=i686 ./build-linux.sh
  artifacts:
    - ffmpeg-${FFMPEG_VERSION}-audio-linux-i686
