image: docker.oxygene.sk/acoustid/chromaprint-build

stages:
  - package

cache:
  paths:
    - ffmpeg-*.tar.bz2

linux i686:
  stage: package
  script: ARCH=i686 ./build-linux.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-linux-*
  tags:
    - docker

linux x86_64:
  stage: package
  script: ARCH=x86_64 ./build-linux.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-linux-*
  tags:
    - docker

linux armv6l:
  stage: package
  script: ARCH=armv6l ./build-linux.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-linux-*
  tags:
    - raspberrypi

windows i686:
  stage: package
  script: ARCH=i686 ./build-windows.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-windows-i686
  tags:
    - docker

windows x86_64:
  stage: package
  script: ARCH=x86_64 ./build-windows.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-windows-x86_64
  tags:
    - docker

macos i386:
  stage: package
  script: ARCH=i386 ./build-macos.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-macos-**
  tags:
    - osx

macos x86_64:
  stage: package
  script: ARCH=x86_64 ./build-macos.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-macos-*
  tags:
    - osx
