image: docker.oxygene.sk/acoustid/chromaprint-build

stages:
  - package

cache:
  paths:
    - ffmpeg-*.tar.bz2

linux i686:
  stage: package
  script: ARCH=i686 ./build-linux.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-linux-*
    expire_in: 7d
  tags:
    - docker

linux x86_64:
  stage: package
  script: ARCH=x86_64 ./build-linux.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-linux-*
    expire_in: 7d
  tags:
    - docker

linux armhf:
  stage: package
  script: ARCH=armhf ./build-linux.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-linux-*
    expire_in: 7d
  tags:
    - raspberrypi

windows i686:
  stage: package
  script: ARCH=i686 ./build-windows.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-windows-i686
    expire_in: 7d
  tags:
    - docker

windows x86_64:
  stage: package
  script: ARCH=x86_64 ./build-windows.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-windows-x86_64
    expire_in: 7d
  tags:
    - docker

macos i386:
  stage: package
  script: ARCH=i386 ./build-macos.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-macos-**
    expire_in: 7d
  tags:
    - osx

macos x86_64:
  stage: package
  script: ARCH=x86_64 ./build-macos.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-macos-*
    expire_in: 7d
  tags:
    - osx
