image: docker.oxygene.sk/acoustid/chromaprint-build

cache:
  paths:
    - ffmpeg-*.tar.bz2

build:linux-i686:
  stage: build
  script: ARCH=i686 ./build-linux.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-linux-i686
  tags:
    - docker

build:linux-x86_64:
  stage: build
  script: ARCH=x86_64 ./build-linux.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-linux-x86_64
  tags:
    - docker

build:windows-i686:
  stage: build
  script: ARCH=i686 ./build-windows.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-windows-i686
  tags:
    - docker

build:windows-x86_64:
  stage: build
  script: ARCH=x86_64 ./build-windows.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-windows-x86_64
  tags:
    - docker
