image: docker.oxygene.sk/acoustid/chromaprint-build

variables:
  FFMPEG_VERSION: "3.2"

cache:
  paths:
    - ffmpeg-*.tar.bz2

build:linux-i686:
  stage: build
  script: ARCH=i686 ./build-linux.sh
  artifacts:
    paths:
      - ffmpeg-${FFMPEG_VERSION}-audio-linux-i686
  tags:
    - docker
