name: Build static ffmpeg

on:
  push:
  pull_request:

jobs:
  package-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - i686
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get install nasm gcc-multilib
      - name: Build
        run: |
          mkdir artifacts
          ./build-linux.sh
          mv ffmpeg-*-audio-linux-* artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ffmpeg-linux-${{ env.ARCH }}
          path: artifacts/

  package-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - i686
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get install nasm mingw-w64
      - name: Build
        run: |
          mkdir artifacts
          ./build-windows.sh
          mv ffmpeg-*-audio-windows-* artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ffmpeg-windows-${{ env.ARCH }}
          path: artifacts/

  package-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch:
          - x86_64
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: brew install nasm
      - name: Build
        run: |
          mkdir artifacts
          ./build-macos.sh
          mv ffmpeg-*-audio-macos-** artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ffmpeg-macos-${{ env.ARCH }}
          path: artifacts/

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - package-macos
      - package-linux
      - package-windows
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
